"""initial

Revision ID: 059ec95bac54
Revises: 
Create Date: 2026-04-06 22:13:55.965178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '059ec95bac54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=True)
    op.create_table('menu',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_restaurante_id'), 'menu', ['restaurante_id'], unique=False)
    op.create_index(op.f('ix_menu_slug'), 'menu', ['slug'], unique=False)
    op.create_table('conversaciones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('mensajes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_cliente_id'), 'conversaciones', ['cliente_id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('direccion_entrega', sa.String(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia')
    )
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_table('items_pedido',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.String(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('modificadores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pedido_pedido_id'), 'items_pedido', ['pedido_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.String(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('referencia_wompi', sa.String(), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_pedido_id'), 'pagos', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_pedido_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_items_pedido_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_conversaciones_cliente_id'), table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_index(op.f('ix_menu_slug'), table_name='menu')
    op.drop_index(op.f('ix_menu_restaurante_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
